name: OpenWeatherMap
on:
  workflow_dispatch:

jobs:
  weather-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Construir proyecto
        run: dotnet build --configuration Release

      - name: Ejecutar aplicacion con secreto
        run: dotnet run --project WeatherApp
        env:
          OPENWEATHERMAP_APIKEY: ${{ secrets.OPENWEATHERMAP_APIKEY }}
